config/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

from lendr.calculator.views import CalculatorView, CalculatorDetail
from lendr.dashboard.views import DashRedirect, Dashboard


urlpatterns = [
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^admin/', admin.site.urls),
    url(r'^$', DashRedirect, name='root'),
    url(r'^dashboard/$', Dashboard, name='dashboard'),
    url(r'^calculator/$', CalculatorView, name='calculator'),
    url(r'^banks/', include('lendr.banks.urls', namespace='banks')),
    url(r'^clients/', include('lendr.clients.urls', namespace='clients')),
    url(r'^loans/', include('lendr.loans.urls', namespace='loans')),
]

lendr/banks/urls.py
from django.conf.urls import url

from . import views
urlpatterns = [
    # {% url 'banks:bank_details' bank.uuid %}
    url(
        regex=r'^$',
        view=views.AllBanksView.as_view(),
        name='all',
    ),
    url(
        regex=r'^bank/(?P<uuid>[0-9A-Za-z]{9,})/rename$',
        view=views.BankRenameView.as_view(),
        name='bank_rename',
    ),
    url(
        regex=r'^bank/(?P<uuid>[0-9A-Za-z]{9,})$',
        view=views.BankDetailView.as_view(),
        name='bank_details',
    ),
    url(
        regex=r'^bank/(?P<uuid>[0-9A-Za-z]{9,})/deposit$',
        view=views.BankDepositView,
        name='bank_deposit'
    ),
    url(
        regex=r'^bank/(?P<uuid>[0-9A-Za-z]{9,})/widthraw$',
        view=views.BankWidthrawView,
        name='bank_widthraw'
    ),
    url(
        regex=r'^bank/(?P<uuid>[0-9A-Za-z]{9,})/transfer$',
        view=views.BankTransferView,
        name='bank_transfer'
    ),
    url(
        regex=r'^bank/(?P<uuid>[0-9A-Za-z]{9,})/new_client$',
        view=views.BankNewClientView.as_view(),
        name='bank_new_client',
    ),
    url(
        regex=r'^bank/(?P<uuid>[0-9A-Za-z]{9,})/transactions$',
        view=views.BankTransactionsView.as_view(),
        name='bank_transactions',
    ),
    url(
        regex=r'^bank/(?P<uuid>[0-9A-Za-z]{9,})/clients$',
        view=views.BankClientsView.as_view(),
        name='bank_clients',
    ),
    url(
        regex=r'^bank/(?P<uuid>[0-9A-Za-z]{9,})/loans$',
        view=views.BankLoansView.as_view(),
        name='bank_loans',
    ),
    url(
        regex=r'^bank/(?P<uuid>[0-9A-Za-z]{9,})/payments$',
        view=views.BankPaymentsView.as_view(),
        name='bank_payments',
    ),
    url(
        regex=r'^new$',
        view=views.CreateBankView.as_view(),
        name='new',
    ),
]

lendr/clients/urls.py
from django.conf.urls import url

from . import views
urlpatterns = [
    url(
        regex=r'^client/(?P<uuid>[0-9A-Za-z]{9,})/new_loan$',
        view=views.NewClientLoan.as_view(),
        name='client_new_loan',
    ),
    url(
        regex=r'^client/(?P<uuid>[0-9A-Za-z]{9,})/add_note$',
        view=views.ClientAddComment.as_view(),
        name='client_add_note',
    ),
    url(
        regex=r'^client/(?P<uuid>[0-9A-Za-z]{9,})/delete$',
        view=views.ClientDeleteView.as_view(),
        name='client_delete',
    ),
    url(
        regex=r'^$',
        view=views.AllClientsView.as_view(),
        name='all',
    ),
    url(
        regex=r'^client/(?P<uuid>[0-9A-Za-z]{9,})/edit_profile$',
        view=views.ClientEditProfile.as_view(),
        name='client_edit_profile',
    ),
    url(
        regex=r'^client/(?P<uuid>[0-9A-Za-z]{9,})/(?P<tab>.*)$',
        view=views.ClientDetailView.as_view(),
        name='client_details',
    ),
]

lendr/loans/urls.py
from django.conf.urls import url

from . import views
urlpatterns = [
    url(
        regex=r'^$',
        view=views.AllLoansView.as_view(),
        name='all',
    ),
    url(
        regex=r'^released$',
        view=views.ReleasedLoansList.as_view(),
        name='released',
    ),
    url(
        regex=r'^closed$',
        view=views.CloseLoansList.as_view(),
        name='closed',
    ),
    url(
        regex=r'^loan/(?P<uuid>[0-9A-Za-z]{9,})$',
        view=views.LoanDetailView.as_view(),
        name='loan_details',
    ),
    url(
        regex=r'^loan/(?P<uuid>[0-9A-Za-z]{9,})/paybalance$',
        view=views.PayOutstandingBalance,
        name='loan_pay_balance',
    ),
    url(
        regex=r'^loan/(?P<uuid>[0-9A-Za-z]{9,})/unpaybalance$',
        view=views.UnpayOutstandingBalance,
        name='loan_unpay_balance',
    ),
    url(
        regex=r'^loan/(?P<uuid>[0-9A-Za-z]{9,})/release/confirm$',
        view=views.ReleaseLoanConfirm,
        name='loan_release_confirm',
    ),
    url(
        regex=r'^loan/(?P<uuid>[0-9A-Za-z]{9,})/(?P<date>\d{4}-\d{2}-\d{2})/release$',
        view=views.ReleaseLoan,
        name='loan_release',
    ),
    url(
        regex=r'^loan/(?P<uuid>[0-9A-Za-z]{9,})/close/confirm$',
        view=views.CloseLoanConfirm,
        name='loan_close_confirm',
    ),
    url(
        regex=r'^loan/(?P<uuid>[0-9A-Za-z]{9,})/close$',
        view=views.CloseLoan,
        name='loan_close',
    ),
    url(
        regex=r'^loan/(?P<uuid>[0-9A-Za-z]{9,})/full/confirm$',
        view=views.FullPaymentConfirm,
        name='loan_full_confirm',
    ),
    url(
        regex=r'^loan/(?P<uuid>[0-9A-Za-z]{9,})/delete$',
        view=views.LoanDelete.as_view(),
        name='loan_delete',
    ),
    url(
        regex=r'^loan/(?P<uuid>[0-9A-Za-z]{9,})/full$',
        view=views.FullPaymentLoan,
        name='loan_full',
    ),
    url(
        regex=r'^loan/(?P<uuid>[0-9A-Za-z]{9,})/(?P<pay_uuid>[0-9A-Za-z]{9,})/pay$',
        view=views.Pay,
        name='loan_pay',
    ),
    url(
        regex=r'^loan/(?P<uuid>[0-9A-Za-z]{9,})/(?P<pay_uuid>[0-9A-Za-z]{9,})/applyInterest$',
        view=views.ApplyInterest,
        name='loan_apply_interest',
    ),
    url(
        regex=r'^loan/(?P<uuid>[0-9A-Za-z]{9,})/(?P<pay_uuid>[0-9A-Za-z]{9,})/unpay$',
        view=views.Unpay,
        name='loan_unpay',
    ),
    url(
        regex=r'^loan/(?P<uuid>[0-9A-Za-z]{9,})/add_payment$',
        view=views.AddPayment.as_view(),
        name='loan_add_payment',
    ),
    url(
        regex=r'^loan/(?P<uuid>[0-9A-Za-z]{9,})/(?P<pay_uuid>[0-9A-Za-z]{9,})/delete_payment$',
        view=views.DeletePayment.as_view(),
        name='loan_delete_payment',
    ),
    url(
        regex=r'^loan/(?P<uuid>[0-9A-Za-z]{9,})/(?P<pay_uuid>[0-9A-Za-z]{9,})/update_payment$',
        view=views.UpdatePayment.as_view(),
        name='loan_update_payment',
    ),
    url(
        regex=r'^loan/(?P<uuid>[0-9A-Za-z]{9,})/(?P<pay_uuid>[0-9A-Za-z]{9,})/late$',
        view=views.MarkLate,
        name='loan_mark_late',
    ),
    url(
        regex=r'^late$',
        view=views.AllLatePaymentsView.as_view(),
        name='late_payments',
    ),
    url(
        regex=r'^query/$',
        view=views.QueryPayments,
        name='query_form',
    ),
    url(
        regex=r'^query/(?P<start_date>\d{4}-\d{2}-\d{2})/(?P<end_date>\d{4}-\d{2}-\d{2})$',
        view=views.CustomPaymentsViewer.as_view(),
        name='custom_query_payments',
    ),
]

lendr/calculator/models.py
from django.db import models

# Create your models here.

lendr/loans/models.py
from enum import Enum
import datetime
from decimal import Decimal, ROUND_UP, ROUND_DOWN
from lendr.utils import id_generator

from django.db import models
from django.urls import reverse
from django.db.models import Q

from lendr.clients.models import Client


class Loan(models.Model):
    """ This is a the loan object """
    class STATUS(Enum):
        waiting = ('waiting', 'Waiting')
        released = ('released', 'Released')
        closed = ('closed', 'Closed')

        @classmethod
        def get_value(cls, member):
            return cls[member].value[0]

    class SCHEDULE(Enum):
        weekly = ('weekly', 'Weekly')
        semimonthly = ('semimonthly', 'Semi-monthly')
        monthly = ('monthly', 'Monthly')
        daily = ('daily', 'Daily')

        @classmethod
        def get_value(cls, member):
            return cls[member].value[0]

    class PAYMENT_METHOD(Enum):
        interest_only = ('interest_only', 'Interest Only')
        compound_interest = ('compound_interest', 'Compound interest')

        @classmethod
        def get_value(cls, member):
            return cls[member].value[0]

    uuid = models.CharField(max_length=22,
                            db_index=True, default=id_generator, editable=False)
    borrower = models.ForeignKey(Client)
    status = models.CharField(
        max_length=32, choices=[x.value for x in STATUS], default=STATUS.get_value('waiting'))

    principal = models.DecimalField(
        max_digits=15, decimal_places=2, default=Decimal(0))
    interest_rate = models.DecimalField(
        max_digits=5, help_text="%", decimal_places=2, default=Decimal(0))
    schedule = models.CharField(
        max_length=32, choices=[x.value for x in SCHEDULE], default=None, blank=True, null=True)
    payment_method = models.CharField(
        max_length=32, choices=[x.value for x in PAYMENT_METHOD], default=PAYMENT_METHOD.get_value('compound_interest'), blank=True, null=True)
    term = models.DecimalField(
        verbose_name="Term", help_text="Months. (30 days = Month)", max_digits=5, decimal_places=0, default=Decimal(0), blank=True, null=True)

    past_due = models.DecimalField(help_text="The previous amount due",
                                   max_digits=10, decimal_places=2, default=Decimal(0))

    grace_period = models.IntegerField(
        help_text="In days", default=3)
    late_fee_rate = models.DecimalField(
        max_digits=10, decimal_places=2, default=Decimal('2.5'))
    processing_fee = models.DecimalField(
        max_digits=10, decimal_places=2, default=Decimal('0'))
    insurance_fee = models.DecimalField(
        max_digits=10, decimal_places=2, default=Decimal('0'))
    notarial_fee = models.DecimalField(
        max_digits=10, decimal_places=2, default=Decimal('0'))

    created_date = models.DateTimeField(auto_now=True)
    released_date = models.DateField(
        help_text="The Loan's release date", default=None, blank=True, null=True)

    expected = models.DecimalField(help_text="The expected uncollected amount used by equal payment loans",
                                   max_digits=10, decimal_places=2, default=Decimal(0))

    collected = models.DecimalField(help_text="The total collected amount, used by equal payment loans",
                                    max_digits=10, decimal_places=2, default=Decimal(0))

    outstanding_balance = models.DecimalField(help_text="The principal loan amount used by interest-only loans",
                                              max_digits=10, decimal_places=2, default=Decimal(0))

    def pay_outstanding_balance(self, money):
        """ Deduct the amount of the outstanding balance """
        self.outstanding_balance -= money
        self.save(update_fields=['outstanding_balance'])
        self.borrower.branch.pay(
            money, self.borrower.full_name())

    def unpay_outstanding_balance(self, money):
        """ Return the amount to the outstanding balance """
        self.outstanding_balance += money
        self.save(update_fields=['outstanding_balance'])
        self.borrower.branch.unpay(
            money, self.borrower.full_name())

    def get_absolute_url(self):
        return reverse('loans:loan_details', kwargs={'uuid': self.uuid})

    def total_number_of_payments(self):
        """ Returns the total number of payments for the loan """
        return self.payments_per_month() * self.term

    def deducted_fee(self):
        """ Returns the deducted fee """
        return (self.processing_fee + self.notarial_fee + self.insurance_fee)

    def payment_frequency(self):
        """ Returns the number of days until a payment is due """
        if self.schedule == "weekly":
            return Decimal('7')
        elif self.schedule == "daily":
            return Decimal('1')
        elif self.schedule == "semimonthly":
            return Decimal('15')
        elif self.schedule == "monthly":
            return Decimal('30')

    def proceeds(self):
        """
        Returns the proceed amount that is released to the client
        Proceeds = principal - (principal * interest)
        """
        # Subtract processing fee, notarial fee, and insurance fee
        return (self.principal - self.interest()) - (self.insurance_fee + self.notarial_fee + self.processing_fee)
        #return (self.principal) - (self.insurance_fee + self.notarial_fee + self.processing_fee)

    def interest(self):
        """ Returns the interest of principal """
        out = self.principal * (self.interest_rate / Decimal(100))
        return out.quantize(Decimal('1.'), rounding=ROUND_UP)

    def amount_per_payment(self):
        """ Returns the amount due per payment """
        total_loan = self.total_loan()
        print(total_loan, self.total_number_of_payments())
        # int_p = (self.interest_rate / Decimal(100)) * self.principal
        # sub = total_loan - int_p
        out = total_loan / self.total_number_of_payments()
        return out.quantize(Decimal('.01'), rounding=ROUND_DOWN)

    def total_interest(self):
        """ Returns the interest of the entire loan """
        return (self.interest() * self.term)

    def total_loan(self):
        """ Returns the total loan """
        return self.total_interest() + self.principal

    def close(self):
        self.status = self.STATUS.get_value('closed')
        self.save(update_fields=['status'])

    def release(self, date=None):
        """ Release the funds to client. This will generate a payment schedule """
        print("Releasing")
        if self.status != 'released':
            if self.borrower.branch.has_sufficient_funds(self.proceeds()):
                if date is not None:
                    self.released_date = date
                else:
                    self.released_date = datetime.datetime.now().date()
                self.status = self.STATUS.get_value('released')
                self.save(update_fields=['released_date', 'status'])
                print("Release date of loan", self.released_date)

                # Add the outstanding balance if its an interest-only loan
                if self.payment_method == "interest_only":
                    self.outstanding_balance = self.proceeds()
                    self.save(update_fields=['outstanding_balance'])
                # Remove the money from Bank
                self.borrower.branch.release(
                    self.proceeds(), self.borrower.full_name())
                self.generate_payments()
            else:
                raise ValueError(self.borrower.branch.InsufficientFundsMessage)

    def set_past_due(self, money):
        print("Setting past due:", money)
        self.past_due = money
        print("past due:", self.past_due)
        self.save(update_fields=['past_due'])

    def add_to_expected(self, money):
        """ Add money to loan expected field """
        self.expected += money
        self.save(update_fields=['expected'])

    def remove_from_expected(self, money):
        """ Remove money to loan expected field """
        self.expected -= money
        self.save(update_fields=['expected'])

    def payments_per_month(self):
        """ Returns the number of payments per month """
        if self.schedule == 'weekly':
            return Decimal(4)
        elif self.schedule == 'semimonthly':
            return Decimal(2)
        elif self.schedule == 'monthly':
            return Decimal(1)
        elif self.schedule == 'daily':
            return Decimal(30)

    def add_to_collected(self, money):
        """ Add money to loan collected field """
        self.collected += money
        self.save()

    def remove_from_collected(self, money):
        """ Remove money to loan expected field """
        self.collected -= money
        self.save(update_fields=['collected'])

    def generate_payment(self, amount_due, due_date):
        print("due:", due_date)
        Payment.objects.create(
            loan_id=self, amount_due=amount_due, due_date=due_date)

    def add_days(start, days):
        start += datetime.timedelta(days=days)
        return start

    def generate_payments(self):
        payment_frequency = self.payment_frequency()
        num_of_payments = self.total_number_of_payments()
        amount_per_payment = self.amount_per_payment()

        if self.payment_method == "interest_only":
            print("Interst_only: generating payments")
            # If there are outstanding balances
            # Just generate the next payment date
            # Check if there are previous paid payments
            payments = Payment.objects.filter(Q(loan_id=self) & Q(
                paid=True)).order_by("-paid_date")
            print("First payment:", payments)
            if not payments.exists():
                # generate the first payment
                print("generate first payment")
                due_date = Loan.add_days(
                    self.released_date, int(payment_frequency))

lendr/calculator/forms.py
from django import forms
from lendr.loans.models import Loan


class LoanCalculatorForm(forms.Form):
    principal = forms.DecimalField(
        label='Principal', required=True, widget=forms.TextInput(attrs={'class': 'input', 'placeholder': 'e.g. 10000'}))
    interest_rate = forms.DecimalField(
        label='Interest Rate', required=True, widget=forms.TextInput(attrs={'class': 'input', 'placeholder': 'e.g. 2.5'}))
    term = forms.IntegerField(
        label='Term', required=True, widget=forms.TextInput(attrs={'class': 'input', 'placeholder': 'e.g. 6'}))
    schedule = forms.ChoiceField(
        label='Schedule', required=True, choices=[x.value for x in Loan.SCHEDULE])
    applyProceeds = forms.BooleanField(label='Apply Proceeds', required=False)

lendr/templates/loans/_loans_list.html
{% load bank_filters %}
<table class="table is-bordered is-striped">
    <tbody>
        <thead>
            <tr>
                <th>ID</th>
                <th>Status</th>
                <th>Principal</th>
                <th>Proceeds</th>
                <th>Interest Rate</th>
                <th>Schedule</th>
                <th>Payment Method</th>
                <th>Term</th>
                <th>Release Date</th>
                <th>Expected</th>
                <th>Collected</th>
            </tr>
        </thead>{% for tx in loans %}
        <tr>
            <td><a href="{{ tx.get_absolute_url }}">{{ tx.pk }}</a></td>
            <td>{{ tx.status | title }}</td>
            <td>{{ tx.principal | pretty_money:tx.borrower.branch.currency }}</td>
            <td>{{ tx.proceeds | pretty_money:tx.borrower.branch.currency }}</td>
            <td>{{ tx.interest_rate }}%</td>
            <td>{{ tx.schedule | title }}</td>
            <td>{{ tx.get_payment_method_display | title }}</td>
            <td>{{ tx.term | title }}</td>
            <td>{{ tx.released_date | date:"Y/m/d" }}</td>
            <td>{{ tx.expected | pretty_money:tx.borrower.branch.currency }}</td>
            <td>{{ tx.collected | pretty_money:tx.borrower.branch.currency }}</td>

        </tr>
        {% endfor %}
    </tbody>
</table>

lendr/templates/loans/_payment_buttons.html
<div class="field is-grouped has-addons">
    {% if not tx.paid %}
    <p class="control">
        <a href="{% url 'loans:loan_pay' object.uuid tx.uuid %}" class="button is-primary">
            <span class="icon is-small">
                <i class="fa fa-money"></i>
            </span>
            <span>Pay {{ tx.amount_due }}</span>
        </a>
    </p>
    {% endif %} {% if tx.paid and object.status != 'closed' %}
    <p class="control">
        <a href="{% url 'loans:loan_unpay' object.uuid tx.uuid %}" class="button is-blank">
            <span class="icon is-small">
                <i class="fa fa-minus"></i>
            </span>
            <span>Unpay</span>
        </a>
    </p>
    {% endif %} {% if not tx.paid and object.status != 'closed' and tx.is_late and not tx.late_fee_applied %}
    <p class="control">
        <a href="{% url 'loans:loan_mark_late' object.uuid tx.uuid %}" class="button is-danger">
            <span class="icon is-small">
                <i class="fa fa-minus"></i>
            </span>
            <span>Mark Late</span>
        </a>
    </p>
    {% endif %} {% if not tx.paid and object.status != 'closed' and tx.is_late  %}
    <p class="control">
        <a href="{% url 'loans:loan_apply_interest' object.uuid tx.uuid %}" class="button is-danger">
            <span class="icon is-small">
                <i class="fa fa-minus"></i>
            </span>
            <span>Apply Interest</span>
        </a>
    </p>
    {% endif %}

</div>

lendr/templates/loans/_tab_section.html
<section class="section">
    <div class="container">
        <div class="tabs is-medium">
        <ul>
            <li class="{% if tab == "loan" %}is-active{% endif %}"><a href="{{ object.get_absolute_url }}">Loans</a></li>
            <li class="{% if tab == "profile" %}is-active{% endif %}"><a href="{% url 'clients:client_details' uuid=object.uuid tab="profile"%}">Profile</a></li>
            <li class="{% if tab == "comments" %}is-active{% endif %}"><a href="{% url 'clients:client_details' uuid=object.uuid tab="comments"%}">Comments</a></li>
        </ul>
        </div>
        {% if loans and tab == "loan" %} {% include "loans/_loans_list.html" %} {% endif %}
        {% if notes and tab == "comments" %} {% include "clients/_notes_list.html" %} {% endif %}
        {% if tab == "profile" %} {% include "clients/_profile.html" %} {% endif %}
    </div>
</section>

lendr/templates/loans/close_confirm.html
{% extends 'base.html' %} {% load bank_filters %} {% block title %}Release Loan {{ loan.pk }}{% endblock %} {############}
{% block content %}
<section class="section">
    <div class="container">
        <div class="columns">
            <div class="column">
            </div>
            <div class="column">
                <h1 class="title">
                    Close Loan {{ loan.pk }}
                </h1>
                <p>Are you sure you want to close this loan?</p>
                <p>This means the loan is not active anymore!</p>
                <strong>Once closed, it cannot be undone!</strong>
                <br>
                <div class="field is-grouped">
                    <a class="button is-success" href="{% url 'loans:loan_close' loan.uuid %}">Yes, Close it</a>
                    <a class="button is-danger" href="{{ loan.get_absolute_url }}">No, Never Mind</a>
                </div>

            </div>
            <div class="column">
            </div>
        </div>
    </div>
</section>
{% endblock %}

lendr/templates/loans/details.html
 {% load bank_filters %}

<table class="table is-bordered is-striped is-narrow">
    <tbody>
        <tr>
            <th>Borrower</th>
            <td><a href="{{ object.borrower.get_absolute_url }}">{{ object.borrower.full_name | title }}</a></td>
        </tr>
        <tr>
            <th>Branch</th>
            <td><a href="{{ object.borrower.branch.get_absolute_url }}">{{ object.borrower.branch.name }}</a></td>
        </tr>
        <tr>
            <th>Status</th>
            <td>{{ object.status | title }}</a>
            </td>
        </tr>
        <tr>
            <th>Created Date</th>
            <td>{{ object.created_date | date:"Y/m/d" }}</a>
            </td>
        </tr>
        {% if object.status == 'released' %}
        <tr>
            <th>Release Date</th>
            <td>{{ object.released_date | date:"Y/m/d" }}</a>
            </td>
        </tr>

        {% endif %}
        <tr>
            <th>Principal</th>
            <td>{{ object.principal | pretty_money:object.borrower.branch.currency }}</td>
        </tr>
        <tr>
            <th>Interest Rate</th>
            <td>{{ object.interest_rate }}%</td>
        </tr>
        <tr>
            <th>Late Fee Rate</th>
            <td>{{ object.late_fee_rate }}%</td>
        </tr>
        <tr>
            <th>Grace Period</th>
            <td>{{ object.grace_period }} day{{ object.grace_period|pluralize }}</td>
        </tr>
        <tr>
            <th>Term</th>
            <td>{{ object.term }} month{{ object.term|pluralize }}</td>
        </tr>
        <tr>
            <th>Schedule</th>
            <td>{{ object.schedule | title }}</td>
        </tr>
        <tr>
            <th>Payment Method</th>
            <td>{{ object.get_payment_method_display | title }}</td>
        </tr>
    </tbody>
</table>

lendr/templates/loans/full_confirm.html
{% extends 'base.html' %} {% load bank_filters %} {% block title %}Release Loan {{ loan.pk }}{% endblock %} {############}
{% block content %}
<section class="section">
    <div class="container">
        <div class="columns">
            <div class="column">
            </div>
            <div class="column">
                <h1 class="title">
                    Full Payment Recieved on Loan {{ loan.pk }}
                </h1>
                <h3 class="subtitle">Total Collected: {{ loan.collected | pretty_money:loan.borrower.branch.currency }}</h3>
                {% if loan.payment_method == "interest_only" %}
                    <h3 class="subtitle">Outstanding Balance: {{ loan.outstanding_balance | pretty_money:loan.borrower.branch.currency }}</h3>
                {% elif loan.payment_method == "compound_interest" %}
                    <h3 class="subtitle">Total Expected: {{ loan.expected | pretty_money:loan.borrower.branch.currency }}</h3>
                {% endif %}
                <p>Are you sure you want to mark this loan as complete?</p>
                <p>This means the full payment was recieved.</p>
                <p>The loan will be closed once a full payment is recieved</p>
                <strong>Once it is fully paid, it cannot be undone!</strong>
                <br>
                <div class="field is-grouped">
                    <a class="button is-success" href="{% url 'loans:loan_full' loan.uuid %}">Yes, I have recieved the full payment</a>
                    <a class="button is-danger" href="{{ loan.get_absolute_url }}">No, Never Mind</a>
                </div>

            </div>
            <div class="column">
            </div>
        </div>
    </div>
</section>
{% endblock %}

lendr/templates/loans/loan_update_payment.html
{% extends 'base.html' %} {% load bank_filters %} {% block title %}Update Payment {{ payment.pk }}{% endblock %} {% block content %}
<section class="section">
    <div class="container">
        <div class="columns">
            <div class="column is-one-quarter">
                <h1 class="title">
                    Update Payment {{ payment.pk }}
                </h1>
                <br>
                <p>This Payment is {% if not payment.is_late %}not{% endif %} late</p>
                <p>This Payment is {% if not payment.paid %}not{% endif %} paid</p>
                <br>
                <form method="post">{% csrf_token %} {{ form.non_field_errors }}
                    <div class="field">
                    </div>
                    <div class="field">
                        <div class="control">
                            {{ form.as_p }}
                        </div>
                    </div>
                    <div class="field">
                        <div class="control">
                            <button class="button is-primary">Update</button>
                            <a class="button is-black" href="{{ object.get_absolute_url }}">Cancel</a>
                        </div>
                    </div>
                    <div class="field">
                        <div class="control">
                            <a class="button is-danger" href="{% url 'loans:loan_delete_payment' object.uuid payment.uuid %}">Delete This Payment</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

lendr/templates/loans/payments.html
 {% load bank_filters %}
<h3 class="subtitle">{{ object.get_payment_method_display }}</h3>
<table class="table is-bordered is-striped is-narrow">
    <tbody>
        <thead>
            <tr>
                <th>#</th>
                <th>ID</th>
                <th>Due Date</th>
                <th>Amount Due</th>
                <th>Paid</th>
                <th>Paid Date</th>
                <th>Late</th>
                <th>Actions</th>
            </tr>
        </thead>{% for tx in payments %}
        <tr>
            <td><a href="{{ tx.get_absolute_url }}">{{ forloop.counter }}</a></td>
            <td>{{ tx.pk }}</td>
            <td>{{ tx.due_date | date:"Y/m/d" }}</td>
            <td {% if tx.late_fee_applied %}class="is-marked-late"{% endif %}>{{ tx.amount_due | pretty_money:object.borrower.branch.currency }}</td>
            <td>{{ tx.paid }}</td>
            <td>{{ tx.paid_date | date:"Y/m/d" }}</td>
            <td class="{% if tx.is_late or tx.late_fee_applied %}is-error{% else %}is-on-time{% endif %}">{{ tx.is_late }}</td>
            <td>{% include "loans/_payment_buttons.html" %}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>