config/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

from lendr.calculator.views import CalculatorView, CalculatorDetail
from lendr.dashboard.views import DashRedirect, Dashboard


urlpatterns = [
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^admin/', admin.site.urls),
    url(r'^$', DashRedirect, name='root'),
    url(r'^dashboard/$', Dashboard, name='dashboard'),
    url(r'^calculator/$', CalculatorView, name='calculator'),
    url(r'^banks/', include('lendr.banks.urls', namespace='banks')),
    url(r'^clients/', include('lendr.clients.urls', namespace='clients')),
    url(r'^loans/', include('lendr.loans.urls', namespace='loans')),
]

lendr/banks/urls.py
from django.conf.urls import url

from . import views
urlpatterns = [
    # {% url 'banks:bank_details' bank.uuid %}
    url(
        regex=r'^$',
        view=views.AllBanksView.as_view(),
        name='all',
    ),
    url(
        regex=r'^bank/(?P<uuid>[0-9A-Za-z]{9,})/rename$',
        view=views.BankRenameView.as_view(),
        name='bank_rename',
    ),
    url(
        regex=r'^bank/(?P<uuid>[0-9A-Za-z]{9,})$',
        view=views.BankDetailView.as_view(),
        name='bank_details',
    ),
    url(
        regex=r'^bank/(?P<uuid>[0-9A-Za-z]{9,})/deposit$',
        view=views.BankDepositView,
        name='bank_deposit'
    ),
    url(
        regex=r'^bank/(?P<uuid>[0-9A-Za-z]{9,})/widthraw$',
        view=views.BankWidthrawView,
        name='bank_widthraw'
    ),
    url(
        regex=r'^bank/(?P<uuid>[0-9A-Za-z]{9,})/transfer$',
        view=views.BankTransferView,
        name='bank_transfer'
    ),
    url(
        regex=r'^bank/(?P<uuid>[0-9A-Za-z]{9,})/new_client$',
        view=views.BankNewClientView.as_view(),
        name='bank_new_client',
    ),
    url(
        regex=r'^bank/(?P<uuid>[0-9A-Za-z]{9,})/transactions$',
        view=views.BankTransactionsView.as_view(),
        name='bank_transactions',
    ),
    url(
        regex=r'^bank/(?P<uuid>[0-9A-Za-z]{9,})/clients$',
        view=views.BankClientsView.as_view(),
        name='bank_clients',
    ),
    url(
        regex=r'^bank/(?P<uuid>[0-9A-Za-z]{9,})/loans$',
        view=views.BankLoansView.as_view(),
        name='bank_loans',
    ),
    url(
        regex=r'^bank/(?P<uuid>[0-9A-Za-z]{9,})/payments$',
        view=views.BankPaymentsView.as_view(),
        name='bank_payments',
    ),
    url(
        regex=r'^new$',
        view=views.CreateBankView.as_view(),
        name='new',
    ),
]

lendr/clients/urls.py
from django.conf.urls import url

from . import views
urlpatterns = [
    url(
        regex=r'^client/(?P<uuid>[0-9A-Za-z]{9,})/new_loan$',
        view=views.NewClientLoan.as_view(),
        name='client_new_loan',
    ),
    url(
        regex=r'^client/(?P<uuid>[0-9A-Za-z]{9,})/add_note$',
        view=views.ClientAddComment.as_view(),
        name='client_add_note',
    ),
    url(
        regex=r'^client/(?P<uuid>[0-9A-Za-z]{9,})/delete$',
        view=views.ClientDeleteView.as_view(),
        name='client_delete',
    ),
    url(
        regex=r'^$',
        view=views.AllClientsView.as_view(),
        name='all',
    ),
    url(
        regex=r'^client/(?P<uuid>[0-9A-Za-z]{9,})/edit_profile$',
        view=views.ClientEditProfile.as_view(),
        name='client_edit_profile',
    ),
    url(
        regex=r'^client/(?P<uuid>[0-9A-Za-z]{9,})/(?P<tab>.*)$',
        view=views.ClientDetailView.as_view(),
        name='client_details',
    ),
]

lendr/loans/urls.py
from django.conf.urls import url

from . import views
urlpatterns = [
    url(
        regex=r'^$',
        view=views.AllLoansView.as_view(),
        name='all',
    ),
    url(
        regex=r'^released$',
        view=views.ReleasedLoansList.as_view(),
        name='released',
    ),
    url(
        regex=r'^closed$',
        view=views.CloseLoansList.as_view(),
        name='closed',
    ),
    url(
        regex=r'^loan/(?P<uuid>[0-9A-Za-z]{9,})$',
        view=views.LoanDetailView.as_view(),
        name='loan_details',
    ),
    url(
        regex=r'^loan/(?P<uuid>[0-9A-Za-z]{9,})/paybalance$',
        view=views.PayOutstandingBalance,
        name='loan_pay_balance',
    ),
    url(
        regex=r'^loan/(?P<uuid>[0-9A-Za-z]{9,})/unpaybalance$',
        view=views.UnpayOutstandingBalance,
        name='loan_unpay_balance',
    ),
    url(
        regex=r'^loan/(?P<uuid>[0-9A-Za-z]{9,})/release/confirm$',
        view=views.ReleaseLoanConfirm,
        name='loan_release_confirm',
    ),
    url(
        regex=r'^loan/(?P<uuid>[0-9A-Za-z]{9,})/(?P<date>\d{4}-\d{2}-\d{2})/release$',
        view=views.ReleaseLoan,
        name='loan_release',
    ),
    url(
        regex=r'^loan/(?P<uuid>[0-9A-Za-z]{9,})/close/confirm$',
        view=views.CloseLoanConfirm,
        name='loan_close_confirm',
    ),
    url(
        regex=r'^loan/(?P<uuid>[0-9A-Za-z]{9,})/close$',
        view=views.CloseLoan,
        name='loan_close',
    ),
    url(
        regex=r'^loan/(?P<uuid>[0-9A-Za-z]{9,})/full/confirm$',
        view=views.FullPaymentConfirm,
        name='loan_full_confirm',
    ),
    url(
        regex=r'^loan/(?P<uuid>[0-9A-Za-z]{9,})/delete$',
        view=views.LoanDelete.as_view(),
        name='loan_delete',
    ),
    url(
        regex=r'^loan/(?P<uuid>[0-9A-Za-z]{9,})/full$',
        view=views.FullPaymentLoan,
        name='loan_full',
    ),
    url(
        regex=r'^loan/(?P<uuid>[0-9A-Za-z]{9,})/(?P<pay_uuid>[0-9A-Za-z]{9,})/pay$',
        view=views.Pay,
        name='loan_pay',
    ),
    url(
        regex=r'^loan/(?P<uuid>[0-9A-Za-z]{9,})/(?P<pay_uuid>[0-9A-Za-z]{9,})/applyInterest$',
        view=views.ApplyInterest,
        name='loan_apply_interest',
    ),
    url(
        regex=r'^loan/(?P<uuid>[0-9A-Za-z]{9,})/(?P<pay_uuid>[0-9A-Za-z]{9,})/unpay$',
        view=views.Unpay,
        name='loan_unpay',
    ),
    url(
        regex=r'^loan/(?P<uuid>[0-9A-Za-z]{9,})/add_payment$',
        view=views.AddPayment.as_view(),
        name='loan_add_payment',
    ),
    url(
        regex=r'^loan/(?P<uuid>[0-9A-Za-z]{9,})/(?P<pay_uuid>[0-9A-Za-z]{9,})/delete_payment$',
        view=views.DeletePayment.as_view(),
        name='loan_delete_payment',
    ),
    url(
        regex=r'^loan/(?P<uuid>[0-9A-Za-z]{9,})/(?P<pay_uuid>[0-9A-Za-z]{9,})/update_payment$',
        view=views.UpdatePayment.as_view(),
        name='loan_update_payment',
    ),
    url(
        regex=r'^loan/(?P<uuid>[0-9A-Za-z]{9,})/(?P<pay_uuid>[0-9A-Za-z]{9,})/late$',
        view=views.MarkLate,
        name='loan_mark_late',
    ),
    url(
        regex=r'^late$',
        view=views.AllLatePaymentsView.as_view(),
        name='late_payments',
    ),
    url(
        regex=r'^query/$',
        view=views.QueryPayments,
        name='query_form',
    ),
    url(
        regex=r'^query/(?P<start_date>\d{4}-\d{2}-\d{2})/(?P<end_date>\d{4}-\d{2}-\d{2})$',
        view=views.CustomPaymentsViewer.as_view(),
        name='custom_query_payments',
    ),
]

lendr/calculator/models.py
from django.db import models

# Create your models here.

lendr/clients/models.py
from django.db import models
from django.shortcuts import reverse

from lendr.utils import id_generator
from lendr.banks.models import Bank
# Create your models here.

class Profile(models.Model):
    title = models.CharField(max_length=500, blank=True, null=True)
    middle_inital = models.CharField(max_length=500, blank=True, null=True)
    birthday = models.CharField(max_length=500, blank=True, null=True)
    age = models.PositiveIntegerField(default=0)
    academic_background = models.CharField(max_length=500, blank=True, null=True)
    home_address = models.CharField(max_length=500, blank=True, null=True)
    residential_status = models.CharField(max_length=500, blank=True, null=True)
    length_of_residence = models.CharField(max_length=20, blank=True, null=True)
    permanent_address = models.CharField(max_length=500, blank=True, null=True)
    telephone_number = models.CharField(max_length=500, blank=True, null=True)

    type_of_employment = models.CharField(max_length=500, blank=True, null=True)
    monthly_income = models.CharField(max_length=500, blank=True, null=True)
    employer = models.CharField(max_length=500, blank=True, null=True)
    employer_address = models.CharField(max_length=500, blank=True, null=True)
    employer_phone = models.CharField(max_length=500, blank=True, null=True)
    employment_length = models.CharField(max_length=500, blank=True, null=True)
    employer_relationship = models.CharField(max_length=500, blank=True, null=True)

    reference_one_full_name = models.CharField(max_length=500, blank=True, null=True)
    reference_one_address = models.CharField(max_length=500, blank=True, null=True)
    reference_one_phone = models.CharField(max_length=500, blank=True, null=True)
    reference_one_relationship = models.CharField(max_length=500, blank=True, null=True)

    reference_two_full_name = models.CharField(max_length=500, blank=True, null=True)
    reference_two_address = models.CharField(max_length=500, blank=True, null=True)
    reference_two_phone = models.CharField(max_length=500, blank=True, null=True)
    reference_two_relationship = models.CharField(max_length=500, blank=True, null=True)

    spouse_full_name = models.CharField(max_length=500, blank=True, null=True)
    spouse_birthday = models.CharField(max_length=500, blank=True, null=True)
    spouse_employer = models.CharField(max_length=500, blank=True, null=True)
    spouse_employer_address = models.CharField(max_length=500, blank=True, null=True)
    spouse_employer_telephone = models.CharField(max_length=500, blank=True, null=True)
    spouse_job_title = models.CharField(max_length=500, blank=True, null=True)
    spouse_monthly_income = models.CharField(max_length=500, blank=True, null=True)
    spouse_telephone = models.CharField(max_length=500, blank=True, null=True)
    spouse_employment_length = models.CharField(max_length=500, blank=True, null=True)


    comaker_full_name = models.CharField(max_length=500, blank=True, null=True)
    comaker_address = models.CharField(max_length=500, blank=True, null=True)
    comaker_telephone = models.CharField(max_length=500, blank=True, null=True)
    comaker_relationship = models.CharField(max_length=500, blank=True, null=True)
    comaker_number_of_dependents = models.CharField(max_length=500, blank=True, null=True)
    comaker_job_title = models.CharField(max_length=500, blank=True, null=True)
    comaker_monthly_income = models.CharField(max_length=500, blank=True, null=True)


    class Meta:
        abstract = True


class Client(Profile):

    timestamp = models.DateTimeField(auto_now=True)
    first_name = models.CharField(max_length=255, blank=False, null=False)
    last_name = models.CharField(max_length=255, blank=False, null=False)
    uuid = models.CharField(max_length=22,
                            db_index=True, default=id_generator, editable=False)
    missed_payments = models.IntegerField(verbose_name="Missed Payments",
                                          default=0, blank=True, null=True)
    branch = models.ForeignKey(
        Bank, related_name='client_bank', on_delete=models.CASCADE, default=None)


    def get_absolute_url(self):
        return reverse('clients:client_details', kwargs={'uuid': self.uuid, 'tab': ""})

    def full_name(self):
        return "{}, {}".format(self.last_name, self.first_name)

    def increment_missed_payments(self):
        self.missed_payments += 1
        self.save(update_fields=['missed_payments'])

    def __str__(self):
        return

    def __unicode__(self):
        return

    class Meta:
        ordering = ["-timestamp"]

class Comments(models.Model):

    timestamp = models.DateTimeField(auto_now=True)
    note = models.TextField(default="")
    client = models.ForeignKey(Client, related_name='client_notes', on_delete=models.CASCADE, default=None)
    poster = models.CharField(max_length=256, blank=True, null=True)

    class Meta:
        ordering = ["-timestamp"]

lendr/dashboard/models.py
from django.db import models

# Create your models here.

lendr/banks/forms.py
from django import forms
from django.forms import ModelForm

from lendr.loans.models import Loan
from lendr.clients.models import Client
from .models import Bank


class NewBankClientForm(ModelForm):
    class Meta:
        model = Client
        fields = ['first_name', 'last_name']
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'input'}),
            'last_name': forms.TextInput(attrs={'class': 'input'}),
        }


class NewBankForm(ModelForm):
    class Meta:
        model = Bank
        fields = ['name', 'currency', 'balance']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'input'}),
            'balance': forms.TextInput(attrs={'class': 'input'}),
        }


class BankDepositForm(forms.Form):
    amount = forms.DecimalField(
        label='Amount', required=True, widget=forms.TextInput(attrs={'class': 'input', 'placeholder': 'e.g. 10000'}))
    reason = forms.CharField(
        label='Comment', widget=forms.TextInput(attrs={'class': 'input'}))


class BankTransferForm(forms.Form):
    CHOICES = []

    # for bank in Bank.objects.all():
    #     out = (bank.name, bank.name)
    #     CHOICES.append(out)

    amount = forms.DecimalField(
        label='Amount', required=True, widget=forms.TextInput(attrs={'class': 'input', 'placeholder': 'e.g. 10000'}))
    banks = forms.ChoiceField(
        label='Banks', required=True, choices=CHOICES)
    reason = forms.CharField(
        label='Comment', widget=forms.TextInput(attrs={'class': 'input'}))

lendr/calculator/views.py
import datetime
from decimal import Decimal

from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import CreateView, DetailView
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse

from lendr.loans.models import Loan, Payment
from lendr.clients.models import Client
from lendr.banks.models import Bank
from .forms import LoanCalculatorForm

# Create your views here.


def CalculatorView(request):
    form = LoanCalculatorForm(request.POST or None)
    data = {}
    if request.method == 'POST':
        if form.is_valid():
            principal = form.cleaned_data['principal']
            interest_rate = form.cleaned_data['interest_rate']
            schedule = form.cleaned_data['schedule']
            term = form.cleaned_data['term']
            applyProceeds = form.cleaned_data['applyProceeds']
            loan = Loan()
            loan.principal = Decimal(principal)
            loan.interest_rate = Decimal(interest_rate)
            loan.schedule = schedule
            loan.term = Decimal(term)
            loan.applyProceeds = applyProceeds
            data["loan"] = loan
            context = {'form': form, 'data': data}
            return render(request, "calculator/loan_form.html", context)

    # if a GET (or any other method) we'll create a blank form
    context = {'form': form, 'data': data}
    return render(request, "calculator/loan_form.html", context)


####### Use this for the actual Loan Creation ########
class OldCalculatorView(CreateView):
    model = Loan
    fields = ['principal', 'interest_rate',
              'schedule', 'term', 'applyProceeds']

    def form_valid(self, form):
        test_bank = Bank.objects.get_or_create(
            name="Test", balance=Decimal(100), currency="CAD")
        test_client, created = Client.objects.get_or_create(
            first_name="Robot", last_name="Test", branch=Bank.objects.first())
        form.instance.borrower = test_client
        return super(CalculatorView, self).form_valid(form)


class CalculatorDetail(DetailView):
    model = Loan

    def get_object(self):
        loan = get_object_or_404(Loan, uuid=self.kwargs['uuid'])
        loan.release()
        return loan

    def get_context_data(self, **kwargs):
        context = super(CalculatorDetail, self).get_context_data(**kwargs)
        payments = Payment.objects.filter(loan_id=self.object)
        context['payments'] = payments
        return context

lendr/dashboard/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from lendr.loans.models import Payment
from lendr.banks.models import Bank, Transaction
from lendr.clients.models import Client


# Create your views here.


def DashRedirect(request):
    """
        The root page:
        If the user is logged in, it will redirect to the actual Dashboard
        If the user is not logged in, it will redirect to the login page
    """
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('dashboard'))
    else:
        msg = "You need to be logged in to proceed"
        messages.info(request, msg)
        return HttpResponseRedirect(reverse('login'))


@login_required(redirect_field_name='DashRedirect')
def Dashboard(request):
    banks = Bank.objects.all()
    transactions = Transaction.objects.all()[:10]
    payments = Payment.objects.filter(paid=False)[:10]
    clients = Client.objects.all()[:10]
    context = {'banks': banks,
               'transactions': transactions, 'clients': clients, 'payments': payments}
    return render(request, "dashboard/index.html", context)

lendr/templates/clients/_action_buttons.html
<div class="field is-grouped has-addons">
    {% if perms.loans.add_loan %}
    <p class="control">
        <a href="{% url 'clients:client_new_loan' object.uuid  %}" class="button is-primary">
            <span class="icon is-small">
                <i class="fa fa-plus"></i>
            </span>
            <span>New Loan</span>
        </a>
    </p>
    {% endif %}
    {% if perms.clients.change_client %}
    <p class="control">
        <a href="{% url 'clients:client_edit_profile' object.uuid  %}" class="button is-primary">
            <span class="icon is-small">
                <i class="fa fa-edit"></i>
            </span>
            <span>Edit Profile</span>
        </a>
    </p>
    {% endif %}
    {% if perms.clients.add_comments and perms.clients.add_notes %}
    <p class="control">
        <a href="{% url 'clients:client_add_note' object.uuid  %}" class="button is-primary">
            <span class="icon is-small">
                <i class="fa fa-sticky-note"></i>
            </span>
            <span>Add Comment</span>
        </a>
    </p>
    {% endif %}
    {% if perms.clients.delete_client %}
    <p class="control">
        <a href="{% url 'clients:client_delete' object.uuid  %}" class="button is-black">
            <span class="icon is-small">
                <i class="fa fa-close"></i>
            </span>
            <span>Delete</span>
        </a>
    </p>
    {% endif %}
</div>

lendr/templates/clients/_notes_list.html
{% load bank_filters %}
<table class="table is-bordered is-striped">
    <tbody>
        <thead>
            <tr>
                <th>Date</th>
                <th>Poster</th>
                <th>Note</th>
            </tr>
        </thead>{% for tx in notes %}
        <tr>
            <td>{{ tx.timestamp | date:"Y/m/d f A" }}</td>
            <td>{{ tx.poster | title }}</td>
            <td>{{ tx.note }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

lendr/templates/clients/_profile.html
 {% load bank_filters %}

<table class="table is-bordered is-striped is-narrow">
    <tbody>
        <tr>
            <th>Title</th>
            <td>{{ object.title }}</td>
        </tr>
        <tr>
            <th>First Name</th>
            <td>{{ object.first_name }}</td>
        </tr>
        <tr>
            <th>Last Name</th>
            <td>{{ object.last_name }}</td>
        </tr>
        <tr>
            <th>Middle Initial</th>
            <td>{{ object.middle_inital }}</td>
        </tr>
        <tr>
            <th>Age</th>
            <td>{{ object.age }}</td>
        </tr>
        <tr>
            <th>Academic Background</th>
            <td>{{ object.academic_background }}</td>
        </tr>
        <tr>
            <th>Home Address</th>
            <td>{{ object.home_address }}</td>
        </tr>
        <tr>
            <th>Permanent Address</th>
            <td>{{ object.permanent_address }}</td>
        </tr>
        <tr>
            <th>Residential Status</th>
            <td>{{ object.residential_status }}</td>
        </tr>
        <tr>
            <th>Telephone Number</th>
            <td>{{ object.telephone_number }}</td>
        </tr>
        <tr>
            <th>Type of Employment</th>
            <td>{{ object.type_of_employment }}</td>
        </tr>
        <tr>
            <th>Monthly Income</th>
            <td>{{ object.monthly_income }}</td>
        </tr>
        <tr>
            <th>Employer</th>
            <td>{{ object.employer }}</td>
        </tr>
        <tr>
            <th>Employer Address</th>
            <td>{{ object.employer_address }}</td>
        </tr>
        <tr>
            <th>Employer Telephone</th>
            <td>{{ object.employer_phone }}</td>
        </tr>
        <tr>
            <th>Employer Relationship</th>
            <td>{{ object.employer_relationship }}</td>
        </tr>
        <tr>
            <th>Employment Length</th>
            <td>{{ object.employment_length }}</td>
        </tr>
    </tbody>
</table>

<h2 class="title">Spouse</h2>

<table class="table is-bordered is-striped is-narrow">
    <tbody>
        <tr>
            <th>Full Name</th>
            <td>{{ object.spouse_full_name }}</td>
        </tr>
        <tr>
            <th>Birthday</th>
            <td>{{ object.spouse_birthday }}</td>
        </tr>
        <tr>
            <th>Employer</th>
            <td>{{ object.spouse_employer }}</td>
        </tr>
        <tr>
            <th>Employment Length</th>
            <td>{{ object.spouse_employment_length }}</td>
        </tr>
        <tr>
            <th>Employer Address</th>
            <td>{{ object.spouse_employer_address }}</td>
        </tr>
        <tr>
            <th>Employer Telephone</th>
            <td>{{ object.spouse_employer_telephone }}</td>
        </tr>
        <tr>
            <th>Job Title</th>
            <td>{{ object.spouse_job_title }}</td>
        </tr>
        <tr>
            <th>Monthly Income</th>
            <td>{{ object.spouse_monthly_income }}</td>
        </tr>
        <tr>
            <th>Telephone Status</th>
            <td>{{ object.spouse_telephone }}</td>
        </tr>
    </tbody>
</table>

<h2 class="title">References</h2>

<table class="table is-bordered is-striped is-narrow">
    <tbody>
        <tr>
            <th>Reference One: Full Name</th>
            <td>{{ object.reference_one_full_name }}</td>
        </tr>
        <tr>
            <th>Reference One: Address</th>
            <td>{{ object.reference_one_address }}</td>
        </tr>
        <tr>
            <th>Reference One: Phone</th>
            <td>{{ object.reference_one_phone }}</td>
        </tr>
        <tr>
            <th>Reference One: Relationship</th>
            <td>{{ object.reference_one_relationship }}</td>
        </tr>
        <tr>
            <th>Reference Two: Full Name</th>
            <td>{{ object.reference_two_full_name }}</td>
        </tr>
        <tr>
            <th>Reference Two: Address</th>
            <td>{{ object.reference_two_address }}</td>
        </tr>
        <tr>
            <th>Reference Two: Phone</th>
            <td>{{ object.reference_two_phone }}</td>
        </tr>
        <tr>
            <th>Reference Two: Relationship</th>
            <td>{{ object.reference_two_relationship }}</td>
        </tr>
    </tbody>
</table>

<h2 class="title">Co-Maker</h2>

<table class="table is-bordered is-striped is-narrow">
    <tbody>
        <tr>
            <th>Full Name</th>
            <td>{{ object.comaker_full_name }}</td>
        </tr>
        <tr>
            <th>Address</th>
            <td>{{ object.comaker_address }}</td>
        </tr>
        <tr>
            <th>Telephone</th>
            <td>{{ object.comaker_telephone }}</td>
        </tr>
        <tr>
            <th>Relationship</th>
            <td>{{ object.comaker_relationship }}</td>
        </tr>
        <tr>
            <th>Number of Dependents</th>
            <td>{{ object.comaker_number_of_dependents }}</td>
        </tr>
        <tr>
            <th>Job Title</th>
            <td>{{ object.comaker_job_title }}</td>
        </tr>
        <tr>
            <th>Monthly Income</th>
            <td>{{ object.comaker_monthly_income }}</td>
        </tr>
        <tr>
            <th>Reference Two: Relationship</th>
            <td>{{ object.reference_two_relationship }}</td>
        </tr>
    </tbody>
</table>

lendr/templates/clients/add_note.html
{% extends 'base.html' %} {% load bank_filters %} {% block title %} Add Comment to Client {% endblock %} {# #############################}
{% block content %}
<section class="section">
    <div class="container">
        <div class="columns">
            <div class="column is-one-quarter">
                <h1 class="title">
                    Add Comment to Client
                </h1>
                <form method="post">{% csrf_token %} {{ form.non_field_errors }}
                    <div class="field">
                        <label class="label">Note</label>
                        <div class="control">
                            {{ form.note }}
                        </div>
                        <div class="field is-grouped">
                            <div class="control">
                                <button class="button is-primary">Save</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

lendr/templates/clients/all.html
{% extends 'base.html' %} {% load bank_filters %} {% block title %} Clients {% endblock %} {# #} {% block content %}

<section class="section">
    <div class="container">
        <h1 class="title">
            Clients
        </h1>
        <br> {% include "pagination.html" %}
        <br>
        <table class="table is-bordered is-striped">
            <tbody>
                <thead>
                    <tr>
                        <th>Full Name</th>
                        <th>Missed Payments</th>
                    </tr>
                </thead>{% for tx in object_list %}
                <tr>
                    <td><a href="{% url 'clients:client_details' tx.uuid "loan" %}">{{ tx.full_name | title }}</a></td>
                    <td>{{ tx.missed_payments }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</section>
{% endblock %}

lendr/templates/clients/client_detail.html
{% extends 'base.html' %} {% load bank_filters %} {% block title %}Client: {{ object.full_name }}{% endblock %} {############}
{% block content %}


<section class="section">
    <div class="container">
        <h1 class="title">
            {{ object.full_name | title }}
        </h1>
        {% include "clients/_action_buttons.html" %}
        <div class="columns">
            <div class="column is-one-quarter">
                <div class="box">
                    <p>Registered Date</p>
                    <h3 class="title">{{ object.timestamp | date:"Y/m/d" }}</h3>
                </div>
            </div>
            <div class="column is-one-quarter">
                <div class="box">
                    <p>Branch</p>
                    <h3 class="title"><a href="{{ object.branch.get_absolute_url }}">{{ object.branch.name }}</a></h3>
                </div>
            </div>
            {% if object.missed_payments %}
            <div class="column is-one-quarter">
                <div class="box">
                    <p>Missed Payments</p>
                    <h3 class="title">{{ object.missed_payments }}</h3>
                </div>
            </div>
            {% endif %}
        </div>
    </div>
</section>
{% include "loans/_tab_section.html" %}
{% endblock %}