config/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

from lendr.calculator.views import CalculatorView, CalculatorDetail
from lendr.dashboard.views import DashRedirect, Dashboard


urlpatterns = [
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^admin/', admin.site.urls),
    url(r'^$', DashRedirect, name='root'),
    url(r'^dashboard/$', Dashboard, name='dashboard'),
    url(r'^calculator/$', CalculatorView, name='calculator'),
    url(r'^banks/', include('lendr.banks.urls', namespace='banks')),
    url(r'^clients/', include('lendr.clients.urls', namespace='clients')),
    url(r'^loans/', include('lendr.loans.urls', namespace='loans')),
]

lendr/banks/urls.py
from django.conf.urls import url

from . import views
urlpatterns = [
    # {% url 'banks:bank_details' bank.uuid %}
    url(
        regex=r'^$',
        view=views.AllBanksView.as_view(),
        name='all',
    ),
    url(
        regex=r'^bank/(?P<uuid>[0-9A-Za-z]{9,})/rename$',
        view=views.BankRenameView.as_view(),
        name='bank_rename',
    ),
    url(
        regex=r'^bank/(?P<uuid>[0-9A-Za-z]{9,})$',
        view=views.BankDetailView.as_view(),
        name='bank_details',
    ),
    url(
        regex=r'^bank/(?P<uuid>[0-9A-Za-z]{9,})/deposit$',
        view=views.BankDepositView,
        name='bank_deposit'
    ),
    url(
        regex=r'^bank/(?P<uuid>[0-9A-Za-z]{9,})/widthraw$',
        view=views.BankWidthrawView,
        name='bank_widthraw'
    ),
    url(
        regex=r'^bank/(?P<uuid>[0-9A-Za-z]{9,})/transfer$',
        view=views.BankTransferView,
        name='bank_transfer'
    ),
    url(
        regex=r'^bank/(?P<uuid>[0-9A-Za-z]{9,})/new_client$',
        view=views.BankNewClientView.as_view(),
        name='bank_new_client',
    ),
    url(
        regex=r'^bank/(?P<uuid>[0-9A-Za-z]{9,})/transactions$',
        view=views.BankTransactionsView.as_view(),
        name='bank_transactions',
    ),
    url(
        regex=r'^bank/(?P<uuid>[0-9A-Za-z]{9,})/clients$',
        view=views.BankClientsView.as_view(),
        name='bank_clients',
    ),
    url(
        regex=r'^bank/(?P<uuid>[0-9A-Za-z]{9,})/loans$',
        view=views.BankLoansView.as_view(),
        name='bank_loans',
    ),
    url(
        regex=r'^bank/(?P<uuid>[0-9A-Za-z]{9,})/payments$',
        view=views.BankPaymentsView.as_view(),
        name='bank_payments',
    ),
    url(
        regex=r'^new$',
        view=views.CreateBankView.as_view(),
        name='new',
    ),
]

lendr/clients/urls.py
from django.conf.urls import url

from . import views
urlpatterns = [
    url(
        regex=r'^client/(?P<uuid>[0-9A-Za-z]{9,})/new_loan$',
        view=views.NewClientLoan.as_view(),
        name='client_new_loan',
    ),
    url(
        regex=r'^client/(?P<uuid>[0-9A-Za-z]{9,})/add_note$',
        view=views.ClientAddComment.as_view(),
        name='client_add_note',
    ),
    url(
        regex=r'^client/(?P<uuid>[0-9A-Za-z]{9,})/delete$',
        view=views.ClientDeleteView.as_view(),
        name='client_delete',
    ),
    url(
        regex=r'^$',
        view=views.AllClientsView.as_view(),
        name='all',
    ),
    url(
        regex=r'^client/(?P<uuid>[0-9A-Za-z]{9,})/edit_profile$',
        view=views.ClientEditProfile.as_view(),
        name='client_edit_profile',
    ),
    url(
        regex=r'^client/(?P<uuid>[0-9A-Za-z]{9,})/(?P<tab>.*)$',
        view=views.ClientDetailView.as_view(),
        name='client_details',
    ),
]

lendr/loans/urls.py
from django.conf.urls import url

from . import views
urlpatterns = [
    url(
        regex=r'^$',
        view=views.AllLoansView.as_view(),
        name='all',
    ),
    url(
        regex=r'^released$',
        view=views.ReleasedLoansList.as_view(),
        name='released',
    ),
    url(
        regex=r'^closed$',
        view=views.CloseLoansList.as_view(),
        name='closed',
    ),
    url(
        regex=r'^loan/(?P<uuid>[0-9A-Za-z]{9,})$',
        view=views.LoanDetailView.as_view(),
        name='loan_details',
    ),
    url(
        regex=r'^loan/(?P<uuid>[0-9A-Za-z]{9,})/paybalance$',
        view=views.PayOutstandingBalance,
        name='loan_pay_balance',
    ),
    url(
        regex=r'^loan/(?P<uuid>[0-9A-Za-z]{9,})/unpaybalance$',
        view=views.UnpayOutstandingBalance,
        name='loan_unpay_balance',
    ),
    url(
        regex=r'^loan/(?P<uuid>[0-9A-Za-z]{9,})/release/confirm$',
        view=views.ReleaseLoanConfirm,
        name='loan_release_confirm',
    ),
    url(
        regex=r'^loan/(?P<uuid>[0-9A-Za-z]{9,})/(?P<date>\d{4}-\d{2}-\d{2})/release$',
        view=views.ReleaseLoan,
        name='loan_release',
    ),
    url(
        regex=r'^loan/(?P<uuid>[0-9A-Za-z]{9,})/close/confirm$',
        view=views.CloseLoanConfirm,
        name='loan_close_confirm',
    ),
    url(
        regex=r'^loan/(?P<uuid>[0-9A-Za-z]{9,})/close$',
        view=views.CloseLoan,
        name='loan_close',
    ),
    url(
        regex=r'^loan/(?P<uuid>[0-9A-Za-z]{9,})/full/confirm$',
        view=views.FullPaymentConfirm,
        name='loan_full_confirm',
    ),
    url(
        regex=r'^loan/(?P<uuid>[0-9A-Za-z]{9,})/delete$',
        view=views.LoanDelete.as_view(),
        name='loan_delete',
    ),
    url(
        regex=r'^loan/(?P<uuid>[0-9A-Za-z]{9,})/full$',
        view=views.FullPaymentLoan,
        name='loan_full',
    ),
    url(
        regex=r'^loan/(?P<uuid>[0-9A-Za-z]{9,})/(?P<pay_uuid>[0-9A-Za-z]{9,})/pay$',
        view=views.Pay,
        name='loan_pay',
    ),
    url(
        regex=r'^loan/(?P<uuid>[0-9A-Za-z]{9,})/(?P<pay_uuid>[0-9A-Za-z]{9,})/applyInterest$',
        view=views.ApplyInterest,
        name='loan_apply_interest',
    ),
    url(
        regex=r'^loan/(?P<uuid>[0-9A-Za-z]{9,})/(?P<pay_uuid>[0-9A-Za-z]{9,})/unpay$',
        view=views.Unpay,
        name='loan_unpay',
    ),
    url(
        regex=r'^loan/(?P<uuid>[0-9A-Za-z]{9,})/add_payment$',
        view=views.AddPayment.as_view(),
        name='loan_add_payment',
    ),
    url(
        regex=r'^loan/(?P<uuid>[0-9A-Za-z]{9,})/(?P<pay_uuid>[0-9A-Za-z]{9,})/delete_payment$',
        view=views.DeletePayment.as_view(),
        name='loan_delete_payment',
    ),
    url(
        regex=r'^loan/(?P<uuid>[0-9A-Za-z]{9,})/(?P<pay_uuid>[0-9A-Za-z]{9,})/update_payment$',
        view=views.UpdatePayment.as_view(),
        name='loan_update_payment',
    ),
    url(
        regex=r'^loan/(?P<uuid>[0-9A-Za-z]{9,})/(?P<pay_uuid>[0-9A-Za-z]{9,})/late$',
        view=views.MarkLate,
        name='loan_mark_late',
    ),
    url(
        regex=r'^late$',
        view=views.AllLatePaymentsView.as_view(),
        name='late_payments',
    ),
    url(
        regex=r'^query/$',
        view=views.QueryPayments,
        name='query_form',
    ),
    url(
        regex=r'^query/(?P<start_date>\d{4}-\d{2}-\d{2})/(?P<end_date>\d{4}-\d{2}-\d{2})$',
        view=views.CustomPaymentsViewer.as_view(),
        name='custom_query_payments',
    ),
]

lendr/banks/models.py
from decimal import Decimal

from lendr.utils import id_generator
from enum import Enum

from django.db import models
from django.db.models import Q


# Create your models here.


class Bank(models.Model):

    class CURRENCY(Enum):
        php = ('PHP', 'PHP')
        cad = ('CAD', 'CAD')
        usd = ('USD', 'USD')

        @classmethod
        def get_value(cls, member):
            return cls[member].value[0]

    InsufficientFundsMessage = "Not enough balance to perform the transaction"

    name = models.CharField(max_length=32, blank=False,
                            null=False, unique=True)
    balance = models.DecimalField(
        max_digits=10, decimal_places=2, default=Decimal(0))
    uuid = models.CharField(max_length=22,
                            db_index=True, default=id_generator, editable=False)

    currency = models.CharField(
        max_length=3, choices=[x.value for x in CURRENCY], default="CAD")

    def add_money(self, money):
        """ Add money into this bank from thin air """
        self.balance = self.balance + money
        self.save(update_fields=['balance'])

    def remove_money(self, money):
        """ Remove money from bank balance """
        self.balance = self.balance - money
        self.save(update_fields=['balance'])

    def has_sufficient_funds(self, money):
        if self.balance >= money:
            return True
        return False

    def widthraw(self, money, reason):
        """ Remove money from self """
        if self.has_sufficient_funds(money):
            self.remove_money(money)
            Transaction.objects.create(
                source_bank=self, destination_bank=self, amount=money, action_type=Transaction.ACTIONS.get_value('widthraw'), reason=reason)
        else:
            raise ValueError(Bank.InsufficientFundsMessage)

    def deposit(self, money, reason):
        """ Deposit money to self """
        self.add_money(money)
        Transaction.objects.create(
            source_bank=self, destination_bank=self, amount=money, action_type=Transaction.ACTIONS.get_value('deposit'), reason=reason)

    def transfer(self, money, destination, reason):
        """ Transfer funds to another bank """
        if self.has_sufficient_funds(money):
            self.remove_money(money)
            destination.add_money(money)
            Transaction.objects.create(
                source_bank=self, destination_bank=destination, amount=money, action_type=Transaction.ACTIONS.get_value('transfer'), reason=reason)
        else:
            raise ValueError(Bank.InsufficientFundsMessage)

    def release(self, money, destination):
        """ Release funds to client """
        if self.has_sufficient_funds(money):
            self.remove_money(money)
            Transaction.objects.create(
                source_bank=self, destination_client=destination, amount=money, action_type=Transaction.ACTIONS.get_value('release'))
        else:
            raise ValueError(Bank.InsufficientFundsMessage)

    def pay(self, money, source):
        """ Recieve a payment from a client """
        self.add_money(money)
        Transaction.objects.create(
            source_client=source, destination_bank=self, amount=money, action_type=Transaction.ACTIONS.get_value('payment'))

    def unpay(self, money, source):
        """ Recieve a payment from a client """
        self.remove_money(money)
        Transaction.objects.create(
            source_bank=self, destination_client=source, amount=money, action_type=Transaction.ACTIONS.get_value('unpay'))

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('banks:bank_details', kwargs={'uuid': self.uuid})

    def transactions(self):
        return Transaction.objects.filter(Q(source_bank__uuid=self.uuid) | Q(destination_bank__uuid=self.uuid))

    def __str__(self):
        return "{}:{}".format(self.name, self.balance)

    def __unicode__(self):
        return


class Transaction(models.Model):
    """Transactions keep track of Bank activity """
    class ACTIONS(Enum):
        deposit = ('deposit', 'Deposit')
        payment = ('payment', 'Payment')
        unpay = ('unpay', 'Unpay')
        widthraw = ('widthraw', 'Widthraw')
        transfer = ('transfer', 'Transfer')
        release = ('release', 'Release')

        @classmethod
        def get_value(cls, member):
            return cls[member].value[0]

    timestamp = models.DateTimeField(auto_now=True)
    uuid = models.CharField(max_length=22,
                            db_index=True, default=id_generator, editable=False)
    source_bank = models.ForeignKey(
        Bank, related_name='source_bank', on_delete=models.CASCADE, default=None, blank=True, null=True)
    destination_bank = models.ForeignKey(
        Bank, related_name='destination_bank', on_delete=models.CASCADE, default=None, blank=True, null=True)
    destination_client = models.CharField(
        max_length=300, default="", blank=True)
    source_client = models.CharField(
        max_length=300, default="", blank=True)
    amount = models.DecimalField(
        max_digits=10, decimal_places=2)
    action_type = models.CharField(
        max_length=8, choices=[x.value for x in ACTIONS])
    reason = models.CharField(max_length=320, default="", null=True, blank=True)

    def __str__(self):
        return

    def __unicode__(self):
        return

    class Meta:
        ordering = ["-timestamp"]

lendr/calculator/models.py
from django.db import models

# Create your models here.

lendr/dashboard/models.py
from django.db import models

# Create your models here.

lendr/calculator/forms.py
from django import forms
from lendr.loans.models import Loan


class LoanCalculatorForm(forms.Form):
    principal = forms.DecimalField(
        label='Principal', required=True, widget=forms.TextInput(attrs={'class': 'input', 'placeholder': 'e.g. 10000'}))
    interest_rate = forms.DecimalField(
        label='Interest Rate', required=True, widget=forms.TextInput(attrs={'class': 'input', 'placeholder': 'e.g. 2.5'}))
    term = forms.IntegerField(
        label='Term', required=True, widget=forms.TextInput(attrs={'class': 'input', 'placeholder': 'e.g. 6'}))
    schedule = forms.ChoiceField(
        label='Schedule', required=True, choices=[x.value for x in Loan.SCHEDULE])
    applyProceeds = forms.BooleanField(label='Apply Proceeds', required=False)

lendr/calculator/views.py
import datetime
from decimal import Decimal

from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import CreateView, DetailView
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse

from lendr.loans.models import Loan, Payment
from lendr.clients.models import Client
from lendr.banks.models import Bank
from .forms import LoanCalculatorForm

# Create your views here.


def CalculatorView(request):
    form = LoanCalculatorForm(request.POST or None)
    data = {}
    if request.method == 'POST':
        if form.is_valid():
            principal = form.cleaned_data['principal']
            interest_rate = form.cleaned_data['interest_rate']
            schedule = form.cleaned_data['schedule']
            term = form.cleaned_data['term']
            applyProceeds = form.cleaned_data['applyProceeds']
            loan = Loan()
            loan.principal = Decimal(principal)
            loan.interest_rate = Decimal(interest_rate)
            loan.schedule = schedule
            loan.term = Decimal(term)
            loan.applyProceeds = applyProceeds
            data["loan"] = loan
            context = {'form': form, 'data': data}
            return render(request, "calculator/loan_form.html", context)

    # if a GET (or any other method) we'll create a blank form
    context = {'form': form, 'data': data}
    return render(request, "calculator/loan_form.html", context)


####### Use this for the actual Loan Creation ########
class OldCalculatorView(CreateView):
    model = Loan
    fields = ['principal', 'interest_rate',
              'schedule', 'term', 'applyProceeds']

    def form_valid(self, form):
        test_bank = Bank.objects.get_or_create(
            name="Test", balance=Decimal(100), currency="CAD")
        test_client, created = Client.objects.get_or_create(
            first_name="Robot", last_name="Test", branch=Bank.objects.first())
        form.instance.borrower = test_client
        return super(CalculatorView, self).form_valid(form)


class CalculatorDetail(DetailView):
    model = Loan

    def get_object(self):
        loan = get_object_or_404(Loan, uuid=self.kwargs['uuid'])
        loan.release()
        return loan

    def get_context_data(self, **kwargs):
        context = super(CalculatorDetail, self).get_context_data(**kwargs)
        payments = Payment.objects.filter(loan_id=self.object)
        context['payments'] = payments
        return context

lendr/dashboard/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from lendr.loans.models import Payment
from lendr.banks.models import Bank, Transaction
from lendr.clients.models import Client


# Create your views here.


def DashRedirect(request):
    """
        The root page:
        If the user is logged in, it will redirect to the actual Dashboard
        If the user is not logged in, it will redirect to the login page
    """
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('dashboard'))
    else:
        msg = "You need to be logged in to proceed"
        messages.info(request, msg)
        return HttpResponseRedirect(reverse('login'))


@login_required(redirect_field_name='DashRedirect')
def Dashboard(request):
    banks = Bank.objects.all()
    transactions = Transaction.objects.all()[:10]
    payments = Payment.objects.filter(paid=False)[:10]
    clients = Client.objects.all()[:10]
    context = {'banks': banks,
               'transactions': transactions, 'clients': clients, 'payments': payments}
    return render(request, "dashboard/index.html", context)

lendr/templates/banks/_action_buttons.html
<div class="field is-grouped has-addons">
    {% if perms.clients.add_client %}
    <p class="control">
        <a href="{% url 'banks:bank_new_client'  object.uuid %}" class="button is-primary">
            <span class="icon is-small">
                <i class="fa fa-user-plus"></i>
            </span>
            <span>New Client</span>
        </a>
    </p>
    {% endif %}
    {% if perms.banks.change_bank %}
    <p class="control">
        <a href="{% url 'banks:bank_rename'  object.uuid %}" class="button is-primary">
            <span class="icon is-small">
                <i class="fa fa-edit"></i>
            </span>
            <span>Rename</span>
        </a>
    </p>
    <p class="control">
        <a href="{% url 'banks:bank_deposit'  object.uuid %}" class="button is-black">
            <span class="icon is-small">
                <i class="fa fa-plus"></i>
            </span>
            <span>Deposit</span>
    </a>
    </p>
    <p class="control">
        <a href="{% url 'banks:bank_widthraw'  object.uuid %}" class="button is-black">
            <span class="icon is-small">
                <i class="fa fa-minus"></i>
            </span>
            <span>Widthraw</span>
    </a>
    </p>
    <p class="control">
        <a href="{% url 'banks:bank_transfer'  object.uuid %}" class="button is-black">
            <span class="icon is-small">
                <i class="fa fa-reply"></i>
            </span>
            <span>Transfer</span>
    </a>
    </p>
    {% endif %}
</div>

lendr/templates/banks/_loans_list.html
 {% load bank_filters %}

<table class="table is-bordered is-striped">
    <tbody>
        <thead>
            <tr>
                <th>ID</th>
                <th>Borrower</th>
                <th>Status</th>
                <th>Principal</th>
                <th>Interest Rate</th>
                <th>Proceeds</th>
                <th>Schedule</th>
                <th>Expected</th>
                <th>Collected</th>
            </tr>
        </thead>{% for loan in loans %}
        <tr>
            <td><a href="{{ loan.get_absolute_url }}">{{ loan.pk }}</a></td>
            <td><a href="{{ loan.borrower.get_absolute_url }}">{{ loan.borrower.full_name | title }}</a></td>
            <td>{{ loan.status | title}}</td>
            <td>{{ loan.principal | pretty_money:loan.borrower.branch.currency }}</td>
            <td>{{ loan.interest_rate }}%</td>
            <td>{{ loan.proceeds | pretty_money:loan.borrower.branch.currency }}</td>
            <td>{{ loan.schedule | title }}</td>
            <td>{{ loan.expected | pretty_money:loan.borrower.branch.currency }}</td>
            <td>{{ loan.collected | pretty_money:loan.borrower.branch.currency }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

lendr/templates/banks/_payments_list.html
 {% load bank_filters %}

<table class="table is-bordered is-striped is-narrow">
    <tbody>
        <thead>
            <tr>
                <th>Loan</th>
                <th>Due Date</th>
                <th>Borrower</th>
                <th>Amount Due</th>
                <th>Paid</th>
                <th>Late</th>
            </tr>
        </thead>{% for payment in payments %}
        <tr>
            <td><a href="{{ payment.loan_id.get_absolute_url }}">{{ payment.loan_id.pk  }}</a></td>
            <td>{{ payment.due_date | date:"Y/m/d" }}</td>
            <td><a href="{{ payment.loan_id.borrower.get_absolute_url }}">{{ payment.loan_id.borrower.full_name | title }}</a></td>
            <td>{{ payment.amount_due | pretty_money:payment.loan_id.borrower.branch.currency }}</td>
            <td>{{ payment.paid }}</td>
            <td class="{% if payment.is_late %}is-error{% else %}is-on-time{% endif %}">{{ payment.is_late }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

lendr/templates/banks/_recent_clients.html
 {% load bank_filters %}

<table class="table is-bordered is-striped is-narrow">
    <tbody>
        <thead>
            <tr>
                <th>Name</th>
                <th>Branch</th>
            </tr>
        </thead>{% for client in clients %}
        <tr>
            <td><a href="{% url 'clients:client_details' client.uuid "loan"%}">{{ client.full_name | title }}</a></td>
            <td>{{ client.branch.name }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

lendr/templates/banks/_recent_transactions.html
 {% load bank_filters %}

<table class="table is-bordered is-striped is-narrow">
    <tbody>
        <thead>
            <tr>
                <th>ID</th>
                <th>Time</th>
                <th>Source</th>
                <th>Destination</th>
                <th>Action</th>
                <th>Amount</th>
                <th>Reason</th>
            </tr>
        </thead>{% for tx in transactions %}
        <tr>
            <td>{{ tx.pk }}</td>
            <td>{{ tx.timestamp | date:"Y/m/d H:i" }}</td>
            {% if tx.source_bank %}
            <td><a href="{% url 'banks:bank_details' tx.source_bank.uuid %}">{{ tx.source_bank.name }}</a></td>
            {% elif tx.source_client %}
            <td>{{ tx.source_client | title }} </td>
            {% endif %} {% if tx.destination_bank %}
            <td><a href="{% url 'banks:bank_details' tx.destination_bank.uuid %}">{{ tx.destination_bank.name }}</a></td>
            {% elif tx.destination_client %}
            <td>{{ tx.destination_client | title }} </td>
            {% endif %}

            <td>{{ tx.action_type | title }}</td>
            {% if tx.source_bank %}
            <td>{{ tx.amount | pretty_money:tx.source_bank.currency }}</td>
            {% elif tx.destination_bank %}
            <td>{{ tx.amount | pretty_money:tx.destination_bank.currency }}</td>
            {% endif %}
            <td>{{ tx.reason }}</td>

        </tr>
        {% endfor %}
    </tbody>
</table>

lendr/templates/banks/all.html
{% extends 'base.html' %} {% load bank_filters %} {% block title %} Banks {% endblock %} {# #} {% block content %}

<section class="section">
    <div class="container">
        <h1 class="title">
            Banks
            <h2 class="subtitle">Total Balance: {{ total_balance | pretty_money:" " }}</h2>
        </h1>
        {% if perms.banks.add_bank %}
        <a class="button is-primary" href="{% url 'banks:new' %}">New Bank</a>
        {% endif %}
        <br> {% include "pagination.html" %}
        <br>
        <table class="table is-bordered is-striped">
            <tbody>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Balance</th>
                    </tr>
                </thead>{% for tx in object_list %}
                <tr>
                    <td><a href="{% url 'banks:bank_details' tx.uuid %}">{{ tx.name }}</a></td>
                    <td>{{ tx.balance | pretty_money:tx.currency }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</section>
{% endblock %}

lendr/templates/banks/bank_rename_form.html
{% extends 'base.html' %} {% load bank_filters %} {% block title %} Rename Bank {% endblock %} {# #############################}
{% block content %}
<section class="section">
    <div class="container">
        <div class="columns">
            <div class="column is-one-quarter">
                <h1 class="title">
                    Rename Bank
                </h1>
                <form method="post">{% csrf_token %} {{ form.non_field_errors }}
                    <div class="field">
                        <label class="label" for="{{ form.name.id_for_label }}">{{ form.name.label }}</label>
                        <div class="control">
                            {{ form.name }}
                        </div>
                        <p class="help is-error">{{ forms.name.errors }}</p>

                        <div class="field is-grouped">
                            <div class="control">
                                <button class="button is-primary">Rename</button>
                            </div>
                            <div class="control">
                                <a href="{% url 'dashboard' %}" class="button is-danger">Cancel</a>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

lendr/templates/banks/clients_list.html
{% extends 'base.html' %} {% load bank_filters %} {% block title %} {{ bank.name }} - All Clients {% endblock %} {### #}
{% block content %}

<section class="section">
    <div class="container">
        <h1 class="title">
            <a href="{{ bank.get_absolute_url }}">{{ bank.name }}</a> Clients
        </h1>
        <p>Total: {{ clients }}</p>
        <p>Viewing: {{ object_list | length }}</p>
        <br> {% include "pagination.html" %}
        <br>
        <table class="table is-bordered is-striped">
            <tbody>
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>First Name</th>
                        <th>Last Name</th>
                        <th>Registed Date</th>
                        <th>Missed Payments</th>
                    </tr>
                </thead>{% for tx in object_list %}
                <tr>
                    <td><a href="{{ tx.get_absolute_url }}">{{tx.uuid }}</a></td>
                    <td>{{ tx.first_name | title }}</td>
                    <td>{{ tx.last_name | title }}</td>
                    <td>{{ tx.timestamp | date:"Y/m/d H:i" }}</td>
                    <td>{{ tx.missed_payments }}</td>

                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</section>
{% endblock %}

lendr/templates/banks/deposit.html
{% extends 'base.html' %} {% load bank_filters %}{% block title %}Deposit to {{ bank.name }}{% endblock %}
{% block content %}
<section class="section">
    <div class="container">
        <div class="columns">
            <div class="column is-one-quarter">
                <h1 class="title">
                    Deposit to {{ bank.name }}
                </h1>
                <strong>Available balance: {{ bank.balance | pretty_money:bank.currency }}</strong>
                <br>
                <form method="post">{% csrf_token %} {{ form.non_field_errors }}
                    <div class="field">

                        <label class="label" for="{{ form.amount.id_for_label }}">{{ form.amount.label }}</label>
                        <div class="control">
                            {{ form.amount }}
                        </div>
                        <p class="help is-error">{{ forms.amount.errors }}</p>
                    </div>
                    <div class="field">

                        <label class="label" for="{{ form.reason.id_for_label }}">{{ form.reason.label }}</label>
                        <div class="control">
                            {{ form.reason }}
                        </div>
                        <p class="help is-error">{{ forms.reason.errors }}</p>
                    </div>
                    <div class="field is-grouped">
                        <div class="control">
                            <button class="button is-primary">Deposit</button>
                        </div>
                        <div class="control">
                            <a href="{% url 'banks:bank_details' bank.uuid %}" class="button is-danger">Cancel</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}